jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      schema: dbt_user
      threads: 24
    prod:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      schema: staging
      threads: 24
